### ISSUE TITLE
Probably merge `v2/feature/jpa-xml` branch to `v1`

### ISSUE THREAD

**Issue by ridoo** [52North/sensorweb-server-db-model#27]
Probably it makes sense to include work from [v2.x/feature/jpa-xml](https://github.com/52North/series-hibernate/tree/v2.x/feature/jpa-xml) in `v1` as 

* `v1` it is still a SNAPSHOT
* actual changes in that branch should be non-conflicting
* data model of both should be the same anyway

**Comment by CarstenHollmann** [comment]
After we are `back to the roots` with v2.x/... we have merged this to v1 and created a v1.1.0 release
